server:
  port: 2020
spring:
  application:
    name: sob_blog_system
  datasource:
    url: jdbc:mysql://39.97.212.229:3307/test?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456