server:
  port: 2021
spring:
  application:
    name: sob_blog_system
  datasource:
    url: jdbc:mysql://39.97.212.229:3307/sob_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 0
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 39.97.212.229
    password: 123456
sob.blog.image.save-path: \home\stardust\sobBlog\images